# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Automated Donator/Developer Builds to the Joyeux Discord Server

on:
  workflow_dispatch:
  push:
    branches:
      - 'feat/**'
      - 'master'
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Run Datagen
        run: ./gradlew runDatagen
      - name: Build
        run: ./gradlew clean build
        #env:
        #  BETA: 1 # exclude assets if it's a beta dev build

      - name: Publish artifacts
        uses: DrTheodor/discord-webhook-upload-action@v1.2
        with:
          url: ${{ secrets.JOYEUX_SERVER }}
          file: 'build/libs/*'
          username: Look Ahead Auto-Compiled Build
          avatar: 'https://github.com/Joyeux-official/lookahead/blob/master/src/main/resources/assets/look-ahead/icon.png?raw=true'
          commit: '> :sparkles: [%MESSAGE%](<%LINK%>) by [%AUTHOR%](<%AUTHOR_LINK%>)! Happy testing!'
          message: |
            <:new1:1253371736510959636><:new2:1253371805734015006> New `${{ github.repository }}` developer build `#${{ github.run_number }}`:
            %COMMITS%